SELECT TOP 2 CITY, LEN(CITY)
FROM STATION
WHERE LEN(CITY) IN (
    SELECT MIN(LEN(CITY))
    FROM STATION
    UNION
    SELECT MAX(LEN(CITY))
    FROM STATION
)
ORDER BY LEN(CITY) DESC , CITY ASC

/*CTE TABLES VERSION*/
SELECT TOP 1 city, LEN(CITY)
FROM station s
WHERE LEN(city) = (SELECT MAX(LEN(city)) FROM station s)
ORDER BY city;
SELECT TOP 1 city, LEN(CITY)
FROM station s
WHERE LEN(city) = (SELECT MIN(LEN(city)) FROM station s)
ORDER BY city;
